[project]
site_name = "GenomeSpy Docs"
site_url = "https://genomespy.app/docs/"
repo_url = "https://github.com/genome-spy/genome-spy"
edit_uri = "edit/master/docs/"
extra_javascript = [{ path = "app/index.js", type = "module" }]
extra_css = ["stylesheets/extra.css"]
nav = [
    "index.md",
    "getting-started.md",
    { "Visualization Grammar" = [
        "grammar/index.md",
        { "Data Input" = [
            "grammar/data/index.md",
            "grammar/data/eager.md",
            "grammar/data/lazy.md",
            "grammar/data/multi-url.md",
        ] },
        { "Transform" = [
            "grammar/transform/index.md",
            "grammar/transform/aggregate.md",
            "grammar/transform/alignment-mismatches.md",
            "grammar/transform/collect.md",
            "grammar/transform/coverage.md",
            "grammar/transform/cross.md",
            "grammar/transform/filter.md",
            { "FilterScoredLabels" = "grammar/transform/filter-scored-labels.md" },
            "grammar/transform/flatten.md",
            "grammar/transform/flatten-cigar.md",
            { "FlattenCompressedExons" = "grammar/transform/flatten-compressed-exons.md" },
            { "FlattenDelimited" = "grammar/transform/flatten-delimited.md" },
            { "FlattenSequence" = "grammar/transform/flatten-sequence.md" },
            "grammar/transform/formula.md",
            { "LinearizeGenomicCoordinate" = "grammar/transform/linearize-genomic-coordinate.md" },
            "grammar/transform/lookup.md",
            { "CoordinateLookup" = "grammar/transform/coordinate-lookup.md" },
            { "MeasureText" = "grammar/transform/measure-text.md" },
            "grammar/transform/pileup.md",
            "grammar/transform/project.md",
            { "RegexExtract" = "grammar/transform/regex-extract.md" },
            { "RegexFold" = "grammar/transform/regex-fold.md" },
            "grammar/transform/sample.md",
            "grammar/transform/stack.md",
            "grammar/transform/window.md",
        ] },
        { "Graphical Marks" = [
            "grammar/mark/index.md",
            "grammar/mark/arrow.md",
            "grammar/mark/link.md",
            "grammar/mark/point.md",
            "grammar/mark/rect.md",
            "grammar/mark/rule.md",
            "grammar/mark/tick.md",
            "grammar/mark/text.md",
        ] },
        "grammar/conditional-encoding.md",
        { "View Composition" = [
            "grammar/composition/index.md",
            { "Concat" = "grammar/composition/concat.md" },
            { "Layer" = "grammar/composition/layer.md" },
            { "Multiscale" = "grammar/composition/multiscale.md" },
        ] },
        { "Scales" = "grammar/scale.md" },
        "grammar/genomic-coordinates.md",
        { "Axes" = "grammar/axis.md" },
        "grammar/title.md",
        { "Legends" = "grammar/legend.md" },
        { "Config And Themes" = "grammar/config.md" },
        "grammar/import.md",
        "grammar/expressions.md",
        "grammar/parameters.md",
        { "Types" = "grammar/types.md" },
    ] },
    { "Working with Sample Collections" = [
        "sample-collections/index.md",
        { "Visualizing" = "sample-collections/visualizing.md" },
        "sample-collections/sample-view-parameters.md",
        "sample-collections/aggregating-samples.md",
        "sample-collections/metadata-sources.md",
        "sample-collections/app-features.md",
        { "Analyzing" = "sample-collections/analyzing.md" },
        "sample-collections/importing-metadata.md",
    ] },
    { "JavaScript API" = [
        "api/index.md",
        "api/embedding.md",
        "api/views.md",
        "api/runtime-state.md",
        "api/inspector.md",
        "api/instance.md",
        "api/embed-options.md",
    ] },
    { "Examples" = [
        "examples/index.md",
        "examples/genomic-data/cytobands.md",
        "examples/genomic-data/indexed-fasta-six-frame-translation.md",
        "examples/genomic-data/refseq-genes.md",
        "examples/genomic-data/gencode-gff3-gene-annotations.md",
        "examples/genomic-data/ascat.md",
        "examples/genomic-data/ascat-algorithm.md",
        "examples/genomic-data/hcc1954-sv-cnv.md",
        "examples/genomic-data/tcga-ov-gistic.md",
        "examples/genomic-data/sashimi-plot.md",
        "examples/genomic-data/dynseq-spi1-bqtl.md",
        "examples/genomic-data/clinvar-variants.md",
        "examples/genomic-data/bam-read-alignments.md",
        "examples/genomic-data/multiple-sequence-alignment.md",
        "examples/genomic-data/genome-browser.md",
    ] },
    "license.md",
]

[project.theme]
logo = "img/bowtie.svg"
custom_dir = "custom_theme/"
features = [
    "navigation.indexes",
    "content.action.edit",
]
palette.primary = "indigo"
font.text = "Lato"

[project.markdown_extensions."markdown.extensions.def_list"]
[project.markdown_extensions."pymdownx.magiclink"]
[project.markdown_extensions."pymdownx.highlight"]
[project.markdown_extensions."pymdownx.superfences"]
[project.markdown_extensions."pymdownx.keys"]
[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.toc]
permalink = true
[project.markdown_extensions."pymdownx.emoji"]
[project.markdown_extensions.mdx_truly_sane_lists]
[project.markdown_extensions.genomespy_extension]
