// @ts-check
/* This file is generated by scripts/generateAgentActionCatalog.mjs. Do not edit manually. */

/** @type {import("./types.js").AgentActionCatalogEntry[]} */
export const generatedActionCatalog = [
    {
        actionType: "sortBy",
        description:
            "Sort samples in descending order by the chosen attribute.",
        payloadType: "SortBy",
        payloadDescription: "Payload for sorting samples by an attribute.",
        payloadFields: [
            {
                name: "attribute",
                type: "AttributeIdentifier",
                description: "Attribute identifier used by the action.",
                required: true,
            },
        ],
        examplePayload: {
            attribute: {
                type: "SAMPLE_ATTRIBUTE",
                specifier: "age",
            },
        },
    },
    {
        actionType: "filterByNominal",
        description: "Retain or remove samples by exact discrete values.",
        payloadType: "FilterByNominal",
        payloadDescription:
            "Retain or remove samples by exact discrete values.",
        payloadFields: [
            {
                name: "attribute",
                type: "AttributeIdentifier",
                description: "Attribute identifier used by the action.",
                required: true,
            },
            {
                name: "values",
                type: "any[]",
                description: "Discrete values to match.",
                required: true,
            },
            {
                name: "remove",
                type: "boolean",
                description:
                    "If true, matching samples are removed instead of retained.",
                required: false,
            },
        ],
        examplePayload: {
            attribute: {
                type: "SAMPLE_ATTRIBUTE",
                specifier: "diagnosis",
            },
            values: ["AML"],
        },
    },
    {
        actionType: "filterByQuantitative",
        description: "Retain or remove samples using a numeric comparison.",
        payloadType: "FilterByQuantitative",
        payloadDescription:
            "Payload for filtering samples by comparing a quantitative attribute against a numeric operand.",
        payloadFields: [
            {
                name: "attribute",
                type: "AttributeIdentifier",
                description: "Attribute identifier used by the action.",
                required: true,
            },
            {
                name: "operator",
                type: "ComparisonOperatorType",
                description: "Comparison operator used for thresholding.",
                required: true,
            },
            {
                name: "operand",
                type: "number",
                description: "Numeric threshold used in the comparison.",
                required: true,
            },
        ],
        examplePayload: {
            attribute: {
                type: "SAMPLE_ATTRIBUTE",
                specifier: "purity",
            },
            operator: "gte",
            operand: 0.6,
        },
    },
    {
        actionType: "groupByNominal",
        description:
            "Group samples by the distinct values of the chosen attribute.",
        payloadType: "GroupByNominal",
        payloadDescription: "Payload for grouping by a categorical attribute.",
        payloadFields: [
            {
                name: "attribute",
                type: "AttributeIdentifier",
                description: "Attribute identifier used by the action.",
                required: true,
            },
        ],
        examplePayload: {},
    },
    {
        actionType: "groupToQuartiles",
        description:
            "Group samples into quartiles by the chosen quantitative attribute.",
        payloadType: "GroupToQuartiles",
        payloadDescription: "Payload for grouping by quartiles.",
        payloadFields: [
            {
                name: "attribute",
                type: "AttributeIdentifier",
                description: "Attribute identifier used by the action.",
                required: true,
            },
        ],
        examplePayload: {},
    },
    {
        actionType: "groupByThresholds",
        description: "Group samples by user-defined numeric thresholds.",
        payloadType: "GroupByThresholds",
        payloadDescription: "Group samples by user-defined numeric thresholds.",
        payloadFields: [
            {
                name: "attribute",
                type: "AttributeIdentifier",
                description: "Attribute identifier used by the action.",
                required: true,
            },
            {
                name: "thresholds",
                type: "Threshold[]",
                description: "Thresholds used to stratify the samples.",
                required: true,
            },
        ],
        examplePayload: {
            attribute: {
                type: "SAMPLE_ATTRIBUTE",
                specifier: "purity",
            },
            thresholds: [
                {
                    operator: "lte",
                    operand: 0.2,
                },
                {
                    operator: "lt",
                    operand: 0.8,
                },
            ],
        },
    },
    {
        actionType: "retainFirstNCategories",
        description:
            "Retain samples from the first n categories in the current ordering.",
        payloadType: "RetainFirstNCategories",
        payloadDescription:
            "Retain samples from the first n categories in the current ordering.",
        payloadFields: [
            {
                name: "attribute",
                type: "AttributeIdentifier",
                description: "Attribute identifier used by the action.",
                required: true,
            },
            {
                name: "n",
                type: "number",
                description: "Number of categories to retain.",
                required: true,
            },
        ],
        examplePayload: {},
    },
];
