// @ts-check
/* This file is generated by scripts/generateAgentActionSummaries.mjs. Do not edit manually. */

/** @type {import("./types.js").AgentActionSummary[]} */
export const generatedActionSummaries = [
    {
        actionType: "sortBy",
        title: "Sort by",
        description:
            "Sort samples in descending order by the chosen attribute.",
    },
    {
        actionType: "filterByNominal",
        title: "Retain samples having diagnosis = AML",
        description: "Retain or remove samples by exact discrete values.",
    },
    {
        actionType: "filterByQuantitative",
        title: "Retain samples having purity ≥ 0.6",
        description: "Retain or remove samples using a numeric comparison.",
    },
    {
        actionType: "groupByNominal",
        title: "Group by",
        description:
            "Group samples by the distinct values of the chosen attribute.",
    },
    {
        actionType: "groupToQuartiles",
        title: "Group by quartiles",
        description:
            "Group samples into quartiles by the chosen quantitative attribute.",
    },
    {
        actionType: "groupByThresholds",
        title: "Group by thresholds",
        description: "Group samples by user-defined numeric thresholds.",
    },
    {
        actionType: "retainFirstNCategories",
        title: "Retain first n categories of ...",
        description:
            "Retain samples from the first n categories in the current ordering.",
    },
];
