"""Generate the index of schema types without dedicated documentation."""

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "utils" / "markdown_extension"))

from extension.extension import types_with_links


SCHEMA_PATTERN = re.compile(r"^SCHEMA\s+(\w+)$", re.MULTILINE)
TYPE_NAME_PATTERN = re.compile(r"^\w+$")
DOCS_DIR = REPO_ROOT / "docs"
SCHEMA_PATH = DOCS_DIR / "schema.json"
TYPES_PATH = DOCS_DIR / "grammar" / "types.md"


def get_documented_types() -> set[str]:
    """Return types expanded with SCHEMA outside the generated index."""
    documented_types: set[str] = set()

    for path in DOCS_DIR.rglob("*.md"):
        if path == TYPES_PATH:
            continue

        documented_types.update(SCHEMA_PATTERN.findall(path.read_text(encoding="utf-8")))

    return documented_types


def get_indexed_types() -> list[str]:
    """Return schema types that do not have dedicated documentation."""
    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    documented_types = get_documented_types()

    return sorted(
        type_name
        for type_name in schema["definitions"]
        if TYPE_NAME_PATTERN.match(type_name)
        and type_name not in documented_types
        and type_name not in types_with_links
    )


def render_types_page(type_names: list[str]) -> str:
    """Render the generated Markdown source for the grammar type index."""
    lines = [
        "# Types Used in the Grammar",
        "",
        "<!-- Generated by `npm run generate:doc-types`. -->",
        "",
        "These types are used in the grammar but are not documented elsewhere.",
        "",
    ]

    for type_name in type_names:
        lines.extend([f"## {type_name}", "", f"SCHEMA {type_name}", ""])

    return "\n".join(lines)


def main() -> int:
    """Generate the type index or check that it is up to date."""
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if docs/grammar/types.md is not up to date",
    )
    args = parser.parse_args()

    rendered = render_types_page(get_indexed_types())
    current = TYPES_PATH.read_text(encoding="utf-8")

    if current == rendered:
        print("docs/grammar/types.md is up to date.")
        return 0
    elif args.check:
        print("docs/grammar/types.md is out of date. Run npm run generate:doc-types.")
        return 1
    else:
        TYPES_PATH.write_text(rendered, encoding="utf-8")
        print("Generated docs/grammar/types.md.")
        return 0


if __name__ == "__main__":
    raise SystemExit(main())
