/**
 * Parameters generated by view macros that must be registered after scale
 * resolution. They are kept outside generated specs.
 *
 * @type {WeakMap<object, import("../spec/parameter.js").Parameter[]>}
 */
const postScaleParams = new WeakMap();

/**
 * @param {object} spec
 * @param {import("../spec/parameter.js").Parameter[]} params
 */
export function setPostScaleParams(spec, params) {
    postScaleParams.set(spec, params);
}

/**
 * @param {object} spec
 * @returns {import("../spec/parameter.js").Parameter[] | undefined}
 */
export function getPostScaleParams(spec) {
    return postScaleParams.get(spec);
}
