name: Build and deploy docs

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown mkdocs-material
          pushd utils/markdown_extension/
          python setup.py build
          python setup.py install
          popd

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Build packages
        run: |
          npm -w @genome-spy/doc-embed run build

      - name: Build JSON schema
        run: npm -w @genome-spy/core build:schema
        
      - name: Build the docs
        run: npm run build:docs
